In [1]:
import torch
print(torch.__version__)

2.8.0+cu126


In [2]:
if torch.cuda.is_available():
  print("gpu is available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available.Using CPU")

GPU is not available.Using CPU


#Create a Tensor

In [3]:
#using empty
a= torch.empty(2,3)

In [4]:
a

tensor([[2.8799e+32, 3.3730e+27, 4.7423e+30],
        [1.0898e+27, 2.6221e+20, 3.0953e-18]])

In [7]:
#check type
type(a)

torch.Tensor

In [8]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
#using rand
torch.rand(2,3)

tensor([[0.3645, 0.2538, 0.9796],
        [0.1017, 0.0756, 0.8173]])

In [11]:
#use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
#other ways

#arange
print("using arange-> ",torch.arange(0,10,2))

#using linspace
print("using linspace-> ",torch.linspace(0,10,10))

#using eye
print("using eye-> ",torch.eye(5))

#using full
print("using full ->",torch.full((3,3),5))

using arange->  tensor([0, 2, 4, 6, 8])
using linspace->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [16]:
#Tensor Shapes

In [17]:
x= torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
x.shape

torch.Size([2, 3])

In [19]:
torch.empty_like(x)

tensor([[6944662201834893925, 2314885530818447916, 7525634142820638752],
        [2314861247312453729, 7958552634293624864, 3255293428008749683]])

In [20]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [22]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [23]:
#Tensor Data Types|

In [25]:
#find data types
x.dtype


torch.int64

In [27]:
#assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [28]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [29]:
#using to()
x.to((torch.float32))

tensor([[1., 2., 3.],
        [4., 5., 6.]])

#Mathematical Operations

1. Scalar Operations

In [30]:
x= torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [31]:
#addition
x+2
#subtraction
x-2
#multiplication
x*3
#division
x/3
#int division
(x*100)//3
#mod
((x*100)/3)%2

#power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

In [32]:
#2. Element wise operation

In [33]:
a=torch.rand(2,3)
b= torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [34]:
c= torch.tensor([1,-2,3,-4])

In [35]:
#absolute
torch.abs(c)

tensor([1, 2, 3, 4])

In [36]:
#negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [37]:
d= torch.tensor([1.9,2.4,3.7,4.4])

In [38]:
#round
torch.round(d)

tensor([2., 2., 4., 4.])

In [39]:
#ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [40]:
#floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [41]:
#clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.4000, 3.0000, 3.0000])

#3. Reduction Operation

In [43]:
e= torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [44]:
#sum
torch.sum(e)
#sum along columns
torch.sum(e,dim=0)
#sum along rows
torch.sum(e,dim=1)

tensor([15.,  9.])

In [45]:
#mean
torch.mean(e)
#mean along col
torch.mean(e,dim=0)


tensor([4., 0., 8.])

In [46]:
#median
torch.median(e)

tensor(0.)

In [47]:
#max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [48]:
#product
torch.prod(e)

tensor(0.)

In [49]:
#standard deviation
torch.std(e)

tensor(4.4272)

In [50]:
#variance
torch.var(e)

tensor(19.6000)

In [51]:
#argmax
torch.argmax(e)

tensor(5)

In [52]:
#argmin
torch.argmin(e)

tensor(1)

#4.Matrix operations

In [54]:
f= torch.randint(size=(2,3),low=0,high=10)
g= torch.randint(size=(3,2),low=0,high=10)

print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [55]:
#matrix multiplication
torch.matmul(f,g)

tensor([[ 87, 119],
        [ 65,  99]])

In [57]:
vector1= torch.tensor([1,2])
vector2= torch.tensor([3,4])

#dot product

torch.dot(vector1,vector2)

tensor(11)

In [58]:
#transpose
torch.transpose(f,0,1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [59]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[5., 9., 8.],
        [9., 7., 9.],
        [2., 6., 7.]])

In [60]:
#determinant
torch.det(h)

tensor(-110.)

In [61]:
#inverse
torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

#5. Comparison Operations

In [64]:
i= torch.randint(size=(2,3),low=0,high=10)
j= torch.randint(size=(2,3),low=0,high=10)

print(i)
print(j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [65]:
#greater than
i>j
#less than
i<j
#equal to
i==j
#not equal to
i!=j
#greater than or equal to

#less than or equal to

tensor([[True, True, True],
        [True, True, True]])

#6.Special Functions|

In [67]:
k= torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[0., 8., 4.],
        [7., 2., 3.]])

In [68]:
#log
torch.log(k)

tensor([[  -inf, 2.0794, 1.3863],
        [1.9459, 0.6931, 1.0986]])

In [69]:
#exp
torch.exp(k)

tensor([[1.0000e+00, 2.9810e+03, 5.4598e+01],
        [1.0966e+03, 7.3891e+00, 2.0086e+01]])

In [70]:
#sqrt
torch.sqrt(k)

tensor([[0.0000, 2.8284, 2.0000],
        [2.6458, 1.4142, 1.7321]])

In [71]:
#sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.9997, 0.9820],
        [0.9991, 0.8808, 0.9526]])

In [72]:
#softmax
torch.softmax(k,dim=0)

tensor([[9.1105e-04, 9.9753e-01, 7.3106e-01],
        [9.9909e-01, 2.4726e-03, 2.6894e-01]])

In [73]:
#relu
torch.relu(k)

tensor([[0., 8., 4.],
        [7., 2., 3.]])

#Inplace Operations

In [74]:
m= torch.rand(2,3)
n= torch.rand(2,3)

print(m)
print(n)

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])
tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])


In [75]:
m.add_(n)

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [76]:
m

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [77]:
n

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [78]:
torch.relu(m)

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [79]:
m.relu_()

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [80]:
m

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

#Copying a Tensor

In [82]:
a= torch.rand(2,3)
a

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [83]:
b=a

In [84]:
b

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [85]:
a[0][0]=0

In [86]:
a

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [87]:
b

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [88]:
id(a)

132685188583648

In [89]:
id(b)

132685188583648

In [90]:
b= a.clone()

In [91]:
a

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [92]:
b

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [93]:
a[0][0]=10

In [94]:
a

tensor([[10.0000,  0.2131,  0.3957],
        [ 0.6017,  0.4234,  0.5224]])

In [95]:
b

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [96]:
id(a)

132685188583648

In [97]:
id(b)

132685188583248

#Reshaping a Tensor

In [99]:
a= torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [100]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [101]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [103]:
b= torch.rand(2,3,4)
b

tensor([[[0.5688, 0.0634, 0.8993, 0.2732],
         [0.3397, 0.1879, 0.5534, 0.2682],
         [0.9556, 0.9761, 0.5934, 0.3124]],

        [[0.9431, 0.8519, 0.9815, 0.1132],
         [0.4783, 0.4436, 0.3847, 0.4521],
         [0.5569, 0.9952, 0.0015, 0.0813]]])

In [104]:
#permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [107]:
#unsqueeze
c= torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [109]:
#squeeze
d=torch.rand(1,20)

#Numpy And PyTorch

In [110]:
import numpy as np


In [111]:
a= torch.tensor([1,2,3])

In [112]:
a

tensor([1, 2, 3])

In [113]:
b= a.numpy()

In [114]:
type(b)

numpy.ndarray

In [118]:
c= np.array([1,2,3])

In [116]:
c

array([1, 2, 3])

In [117]:
torch.from_numpy(c)

tensor([1, 2, 3])